# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  label: English
  weight: 1
  locale: en-us
  contentDir: content/en
  title: 'Erik Sandvig'
  params:
    description: "Erik Sandvig - quantitative ecologist working on population
      trends and shorebird monitoring in Chile."
  menu:
    main:
      - name: Bio
        url: /
        weight: 10
      - name: Projects
        url: projects/
        weight: 20
      - name: News
        url: /#news
        weight: 30
      - name: Publications
        url: /#papers
        weight: 40
      - name: CV
        url: cv/
        weight: 50

es:
  label: Español
  weight: 2
  locale: es-cl
  contentDir: content/es
  title: 'Erik Sandvig'
  params:
    description: "Erik Sandvig - ecólogo cuantitativo, especializado en
      tendencias poblacionales y monitoreo de aves playeras en Chile."
  menu:
    main:
      - name: Biografía
        url: /
        weight: 10
      - name: Proyectos
        url: projects/
        weight: 20
      - name: Noticias
        url: /#news
        weight: 30
      - name: Publicaciones
        url: /#papers
        weight: 40
      - name: CV
        url: cv/
        weight: 50
